language: cpp
addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
    - libgtest-dev
    - g++-8
branches:
  only:
  - master
before_script:
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
script:
- mkdir gtest
- cd gtest
- cmake /usr/src/gtest/
- cmake --build .
- sudo cp *.a /usr/lib/
- cd ..
- mkdir build
- cd build
- cmake  -DCMAKE_BUILD_TYPE=Release ..
- cmake --build .
- cd ..
